### PR TITLE
Add method to automatically create integer IDs

### PR DESCRIPTION
**Pull request by boosh**
Added a method to generates integer resource IDs automatically.

### CODE REVIEW

**Comment by glinton** [comment]
Having automatically generated ids is a good idea, but I'm not loving parsing directory to generate it. It could lead to massive slowdowns. Instead we could generate an id (UUID, timestamp hash, etc...) to avoid the overhead of listing/parsing the directory

**Comment by boosh** [comment]
@glinton yeah i thought about UUIDs, but for my usecase (the datastore behind a slackbot) I need to be able to refer to items by simple IDs. A UUID would be cumbersome to type into slack. The other benefit of integer IDs is creation order is implicit (I'm only really interested in the last 20 or so files, so not having to `ls -l` to find the latest ones is useful).

Perhaps the driver should just be updated to cache the last used auto-generated ID? While auto-generating an ID, it could try to write a new file (not overwrite an existing one), and only fall back to inspecting the filesystem if a file with the next ID already exists. This would be a simple way of improving performance without needing complicated IDs.

**Comment by glinton** [comment]
I think parsing the files in the directory to establish the starting integer is a much better solution than reading every time for sure. Another concern regarding parsing a directory would be if an empty file exists, should scribble free that id up or just move on and take the highest found number then add 1? If you would like to add the bit to parse the directory on startup and determine the id, we can merge that in. Otherwise, i'll update this pr to merge to a feature branch where I'll finish that bit and use what you have for the id use.
Let me know what you prefer/have time for.

**Comment by boosh** [comment]
@glinton I think regarding empty files scribble should just take the next available ID. No point in making too many assumptions about why empty files exist.

One thing I'd probably change is I just picked a largish number of zeros to pad IDs by, but that should probably end up in config on the driver with a method to centralise generating padded IDs. There are a few `fmt.Sprintf()` calls floating around which aren't intuitive, especially in client code.

I'm not going to have time to work on this until at least the week after next, so if you have time please go ahead. 
 
Thanks!

**Comment by glinton** [comment]
Sounds good, I'll get on it

**Pull request merged**
